version: '3'

services:
  redis:
    image: redis
    container_name: redis_session
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  nginx:
    container_name: reverse_proxy
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/letsencrypt/live/choizz-chat.r-e.kr/fullchain.pem
      - ./privkey.pem:/etc/letsencrypt/live/choizz-chat.r-e.kr/privkey.pem
    ports:
      - "80:80"
      - "443:443"

  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=choizz
      - MONGO_INITDB_ROOT_PASSWORD=choizz

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=choizz
      - ME_CONFIG_MONGODB_ADMINPASSWORD=choizz
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo: { }


