spring:
  data:
    mongodb:
      database: choizzdb
      port: 27017
      host: localhost
      username: choizz
      password: ${MONGO_PASSWORD}
      authentication-database: admin

logging:
  level:
    org.springframework.data.mongodb: debug


