spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: on

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 123qweasd
    url: jdbc:mysql://choizz-db.clwna61sgtpo.ap-northeast-2.rds.amazonaws.com:3306/db

  data:
    redis:
      host: localhost
      password: 1234
      port: 6379


    mongodb:
      database: choizzdb
      port: 27017
      host: localhost
      username: choizz
      password: choizz
      authentication-database: admin

  session:
    timeout: 1800

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: none
        secure: on

