spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: on

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: choizz1
    password: 1234
    url: jdbc:mysql://localhost:3306/choizzdb

  data:
    redis:
      host: localhost
      password: 1234
      port: 6379

  session:
    timeout: 1800

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
        same-site: none
        secure: off

