spring:
  jpa:
    hibernate:
      ddl-auto:
    defer-datasource-initialization: on

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: ${MYSQL_PASSWORD }
    url: jdbc:mysql://${DB_HOST}:3306/db

  data:
    redis:
      host: localhost
      password: ${ REDIS_PASSWORD }
      port: 6379


    mongodb:
      database: choizzdb
      port: 27017
      host: localhost
      username: choizz
      password: ${secrets.MONGO_PASSWORD}
      authentication-database: admin

  session:
    timeout: 1800

server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        same-site: none
        secure: on


