spring:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: on

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: choizz
    password: 1234
    url: jdbc:mysql://localhost:3306/choizzdb

  session:
    timeout: 1800

