spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: on

  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/chat
    #    url: jdbc:h2:mem:chattest
    driver-class-name: org.h2.Driver

  session:
    timeout: 18600

#    jdbc:
#      initialize-schema: never
