spring:
  jpa:
    show_sql: true
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: on

  datasource:
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/chat
#    url: jdbc:h2:mem:chattest
    driver-class-name: org.h2.Driver

  data:
    redis:
      host: 127.0.0.1
      password:
      port: 6379

  session:
    redis:
      repository-type: default

    timeout: 1800


#    jdbc:
#      initialize-schema: never
