version: '3'

services:
  mysql-db:
    container_name: mysql
    image: mysql:8
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    restart: unless-stopped

    ports:
      - '3306:3306'

    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

    environment:
      MYSQL_ROOT_HOST: 'choizz-api1.kro.kr'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'choizzdb'
      TZ: Asia/Seoul

  redis:
    image: redis
    container_name: redis_session
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]


  db-admin:
    container_name: db-adminer
    image: adminer:latest
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=mysql-db
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce