# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: ${{ secrets.SECRET_TOKEN }}
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build
        cache-read-only: false
    
    - name: zip project file
      run: zip -r ./chatting-api.zip .

    - name: access to AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./chatting-api.zip s3://${{ secrets.S3_BUCKET_NAME }}/chatting-api.zip

    - name: Deploy to EC2 with CodeDeploy
      run: aws deploy create-deployment
        --application-name codedeploy
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name codedeploy-api
        --s3-location "bucket=${{ secrets.S3_BUCKET_NAME }}, bundleType=zip, key=chatting-api.zip"




    
